### ISSUE TITLE
Users are confused when taxa search shows "text:foo"

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#287]
We've had a few user tickets from people who get many thousands of results for a search that should only show a few records. See https://support.ehelp.edu.au/a/tickets/25402.

This issue is searching for a taxon that is not in the ALA backbone. As a result, it falls-back to a text search like "text:Aus bus" which gets run as "Aus OR Bus" and therefore shows a bazillion records. 

Fixes required:
- [x] Clearly indicate it is NOT a species search but a FULL TEXT search
- [x] Perform a quoted `text:"Aus Bus"` search, not an OR'ed search
- [ ] ~Change the default operator in SOLR config to be AND and not OR~
- [ ] ~Possibly include a "did you mean:" `raw_name:"Aus bus"`~

Update: Shelving last 2 ideas for now, as first 2 fixes may be all that's required for this issue. Can always implement later if feedback suggests they're needed.

**Comment by nickdos** [comment]
WIP so far:
 
![image](https://user-images.githubusercontent.com/532845/49122667-810a6f00-f309-11e8-8317-d3b2c1930bc5.png)

**Comment by elywallis** [comment]
And another related enquiry has just come through the support queue: https://support.ehelp.edu.au/a/tickets/25503

**Comment by nielsklazenga** [comment]
I don't know what 'WIP' means, but the rest looks pretty good. Could you change 'recognised' to 'matched'? Carex kobomugi is a recognised taxon name. It would actually be better to leave out that note entirely.

**Comment by M-Nicholls** [comment]
https://support.ehelp.edu.au/a/tickets/25503 is related although there's a separate issue in that the name the user searching for isn't in our names index yet

**Comment by ansell** [comment]
@nielsklazenga WIP is short for "Work in Progress", so not complete yet

**Comment by nielsklazenga** [comment]
@M-Nicholls Carex kobomugi is also not in the ALA name index, as it does not occur in Australia.

@ansell Thanks

**Comment by ansell** [comment]
I deployed the latest commit above to https://biocache-test.ala.org.au/ if you want to test them out for various searches. As Nick says, it is Work in Progress at this point.

**Comment by elywallis** [comment]
There's a related issue here as well that might be assisted by making it clear how the search is searching in different fields (e.g. AND or OR, can you use " or not etc)
https://support.ehelp.edu.au/a/tickets/25388 

In this case, it's a little more complicated because the request is about searching on a person's name, where their name has changed over their lifetime (the example given is a woman who gets married and changes her name). Advanced search in AVH provides a field to search on Collector but no similar field in Biocache. And no names index to match to.

**Comment by nickdos** [comment]
Hi @elywallis would you mind creating a new issue in this repo for Murray's request. I think it could be a general "enhancement" issue to improve the advanced search interface. Its a tricky one because what Murray is asking for is straight forward if you type the query in by hand (in the URL) but is tough to do in a UI as you end up having a complex form that works some of the time for some of the users (small percent) and leaves the rest of the user base just confused. But I think we could make some small improvements in the short term and delay other changes for when we split out a simpler "simple" interface and a more powerful "expert" interface (UX review suggested this).

**Comment by nickdos** [comment]
- [ ] Found a bug with when the quoted fall-back search returns 0 results - it tries an ORed search but quotes are still present and therefore it gets literally interpreted.

**Comment by nickdos** [comment]
Deployed to prod for `ala-hub` - will do `avh-hub`next.
