### ISSUE TITLE
Explore Your Area - only listing top 50 species per group

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/biocache-hubs#610]
Explore Your Area is now only showing the top 50 species per group, _except for "All species"_. This is happening on [ALA](https://biocache.ala.org.au/explore/your-area), [AVH](https://avh.ala.org.au/explore/your-area) and [Ozcam](https://ozcam.ala.org.au/explore/your-area) explore your area tools. 

Steps to replicate:
1. Go to explore your area, search any location
2. Click on any group (other than "All species") with more than 50 species 
3. Scroll down the list of species, verify that only 50 are showing
![Screenshot 2024-08-12 at 3 00 31 pm](https://github.com/user-attachments/assets/8e42a158-dd4b-4e0d-8bfb-a1bac1b97341)

4. At the bottom of the list, click on 'Show more species'. It now displays "[no species found]":
![Screenshot 2024-08-12 at 2 58 36 pm](https://github.com/user-attachments/assets/378e67c1-efe2-4cfb-826d-3f412b183084)

Other testing notes: I've tested using Chrome, Firefox, Safari and Edge, getting the same results

**Comment by kylie-m** [comment]
Raised via user support
- https://support.ehelp.edu.au/a/tickets/209039

**Comment by nickdos** [comment]
Latest code works fine on local dev setup and I noticed that prod is using an old version of `biocache-hubs`, suggesting this is the cause.

**Comment by kylie-m** [comment]
Hi @nickdos FYI it's also just been flagged by a second user that sorting by name/number is failing. 

I've replicated this on ALA, AVH and Ozcam by:
1. Click on "Common name" to sort by it. Result = "[no species found]
2. Same for "Scientific names" and 
3. Same for "Records"


- Reported by user https://support.ehelp.edu.au/a/tickets/209360

**Comment by nickdos** [comment]
Thanks @kylie-m i did pick that up and fix it as well. The code for both was in the same block and used the  essentially the same logic. Both are fixed and I'll deploy to test later today.

**Comment by nickdos** [comment]
@kylie-m - would you mind testing my fix that is [deployed to test](https://biocache-test.ala.org.au/explore/your-area), please?

**Comment by kylie-m** [comment]
@nickdos working well for me on ALA EYA, I tested the fixed issues plus general test cases on #6 of [Biocache hubs testing docs](https://confluence.csiro.au/display/ALASD/Biocache+UI+%28hubs%29+testing). All passing - thanks again for this! 

Just noting AVH and Ozcam EYA's are still failing on test but I assumed the fix wasn't deployed there

**Comment by nickdos** [comment]
> Just noting AVH and Ozcam EYA's are still failing on test but I assumed the fix wasn't deployed there

Yes, I did not deploy those hubs yet. I just wanted to check this issue and those 2 hubs are not officially supported for "explore your area" - that page exists but is not linked to/from anywhere on those site. So its a ghost page for them.

**Comment by nickdos** [comment]
@qifeng-bai has code reviewed this change

**Comment by kylie-m** [comment]
User support ref:
https://support.ehelp.edu.au/a/tickets/209039
https://support.ehelp.edu.au/a/tickets/209360
https://support.ehelp.edu.au/a/tickets/209512
https://support.ehelp.edu.au/a/tickets/209610
